'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class fact_cab
    Public Property idfact_cab As Integer
    Public Property fecha As Date
    Public Property total As Decimal
    Public Property fpago As String
    Public Property Estado As String
    Public Property idUsuario As Integer

    Public Overridable Property fact_det As ICollection(Of fact_det) = New HashSet(Of fact_det)
    Public Overridable Property usuario As usuario

End Class
