'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class fact_det
    Public Property idfact_det As Integer
    Public Property idfact_cab As Integer
    Public Property Detalle As String
    Public Property Estado As String
    Public Property Precio As Decimal
    Public Property Cantidad As Integer

    Public Overridable Property fact_cab As fact_cab

End Class
