'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class pruebaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=pruebaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property fact_cab() As DbSet(Of fact_cab)
    Public Overridable Property fact_det() As DbSet(Of fact_det)
    Public Overridable Property usuario() As DbSet(Of usuario)

End Class
